name: download artifact from same workflow
on: workflow_dispatch

jobs:
  artifact-upload:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 0 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
          
  download-artifact:
    runs-on: ubuntu-latest
    needs: artifact-upload
    steps:
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: output-log-file

      - name: check file content
        shell: bash
        run: cat output.log
