name: Setting default shell and working directory

on:
  workflow_dispatch

env:
  DAY_OF_WEEK: Monday

jobs:
  this-is-default-location:
    runs-on: ubuntu-latest
    steps:
      - run: pwd
  change-default-location:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ~/
        
    steps:
      - run: pwd

