name: Sharing data between jobs
on: workflow_dispatch

jobs:
  sharingDataBetweenJobs:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 0 > output.log
          ls
          cat output.log
          pwd
