name: Sharing data between jobs
on: workflow_dispatch

jobs:
  sharingDataBetweenJobs:
    runs-on: ubuntu-latest
    steps:
      - shell: bash
        run: |
          expr 1 + 0 > output.log
      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: output-log-file
          path: output.log
